services:
  api:
    container_name: swpr
    restart: always
    build:
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - 1111:1111
    environment:
      APP_DB_HOST: localhost
      APP_DB_PORT: 2345
      APP_DB_DB: swpr
      APP_DB_USERNAME: opannapo
      APP_DB_PASSWORD: opannapo
      APP_SEC_JWTKEY: Test123TestKeyJwt
      APP_SEC_JWT_TTL: 24h
    depends_on:
      db:
        condition: service_healthy
  db:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    container_name: postgres_db_swpr
    restart: always
    environment:
      POSTGRES_USER: opannapo
      POSTGRES_PASSWORD: opannapo
      POSTGRES_DB: swpr
    ports:
      - 2345:5432
    expose:
      - 2345
    volumes:
      - db:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U opannapo" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db:
    driver: local
